common:
    exp_name: kase_exp003
    arch: os2_resnet152
    workers: 1
    batch_size: 24 
    bn_group: 2
    bn_sync_stats: True
    pretrained: True
    num_classes: 12
    max_iter: 380000
    warmup_steps: 0
    warmup_lr: 0.2
    base_lr: 0.00001
    lr_steps: [300000]
    lr_mults: [0.1]
    use_weight: False
    double_softmax: True
    teacher_alpha: 0.99
    momentum: 0.9
    weight_decay: 0.0001
    lr_gamma: 0.1
    val_freq: 100
    print_freq: 10
    cls_balance: 0.01
    load_path:
    fix_constant: True
    constant: 0.001
    th: 0.5
    fix_constant: True
    constant: 0.001
    double_softmax: False
    lambda_uk: 1
    lambda_entropy: 1
    cls_balance: 0.01
    lambda_aug: 10
    aug_thresh: 0.9

    epsilon: 0.02
    enp_known_weight: True
    prob_uk: False

    src_hflip: True
    src_xlat_range: 0.0
    src_affine_std: 0.0
    src_rot_std: 0
    random_crop: True
    padding: [16, 16]

    src_intens_scale_range_lower: 0.75
    src_intens_scale_range_upper: 1.333
    src_colour_rot_std: 0
    src_colour_off_std: 0
    src_greyscale: False 
    src_scale_u_range: [0.75, 1.333]
    src_cutout_prob: 0.0
    src_cutout_size: 0.3


    tgt_hflip: True
    tgt_xlat_range: 0.0
    tgt_affine_std: 0.0
    tgt_rot_std: 0
    tgt_intens_scale_range_lower: 0.75 
    tgt_intens_scale_range_upper: 1.333
    tgt_colour_rot_std: 0
    tgt_colour_off_std: 0
    tgt_greyscale: False 
    tgt_scale_u_range: [0.75, 1.333]
    tgt_cutout_prob: 0.0
    tgt_cutout_size: 0.3
    class_name: [plane, bcycl, bus, car, horse, knife, mcycl, person, plant, sktbd, train, truck, unknown]

    train_source_root: data/visda/train/
    train_target_root: data/visda/validation/
    train_source_source: ./data/visda/list/train_list.txt
    train_target_source: ./data/visda/list/validation_list.txt
    val_root: data/visda/validation/
    val_source: ./data/visda/list/validation_sample_list.txt
