common:
    exp_name: kase_a_d_exp001
    arch: os2_alexnet
    workers: 1
    batch_size: 30
    bn_group: 2
    bn_sync_stats: True
    pretrained: True
    num_classes: 10
    max_iter: 380000
    warmup_steps: 0
    warmup_lr: 0.2
    base_lr: 0.000001
    lr_steps: [300000]
    lr_mults: [0.1]
    use_weight: False
    double_softmax: False
    teacher_alpha: 0.99
    momentum: 0.9
    weight_decay: 0.0001
    lr_gamma: 0.1
    val_freq: 1000
    print_freq: 10
    cls_balance: 0.01
    load_path:
    fix_constant: True
    constant: 0.001
    th: 0.5
    fix_constant: True
    constant: 0.001
    double_softmax: False
    lambda_uk: 10
    lambda_entropy: 5
    cls_balance: 0.01
    lambda_aug: 10
    aug_thresh: 0.6

    epsilon: 0.02
    enp_known_weight: True
    prob_uk: False

    src_hflip: True
    src_xlat_range: 0.0
    src_affine_std: 0.0
    src_rot_std: 0
    random_crop: True
    padding: [16, 16]

    src_intens_scale_range_lower: 1
    src_intens_scale_range_upper: 1
    src_colour_rot_std: 0
    src_colour_off_std: 0
    src_greyscale: False 
    src_scale_u_range: [0.75, 1.333]
    src_cutout_prob: 0.0
    src_cutout_size: 0


    tgt_hflip: True
    tgt_xlat_range: 0.0
    tgt_affine_std: 0.0
    tgt_rot_std: 0
    tgt_intens_scale_range_lower: 1 
    tgt_intens_scale_range_upper: 1
    tgt_colour_rot_std: 0
    tgt_colour_off_std: 0
    tgt_greyscale: False 
    tgt_scale_u_range: [0.75, 1.333]
    tgt_cutout_prob: 0.0
    tgt_cutout_size: 0
    class_name: [plane, bcycl, bus, car, horse, knife, mcycl, person, plant, sktbd, train, truck, unknown]

    train_source_root: data/office
    train_target_root: data/office
    train_source_source: ./data/office/list/amazon_source_list.txt
    train_target_source: ./data/office/list/dslr_target_list.txt
    val_root: data/office
    val_source: ./data/office/list/dslr_target_list.txt
